<div class="theme report">
    <div class="row scrollbarY">
        <div class="title">
            <h2>Thống kê khách hàng</h2>
            <p><span class="text" data-name="statistical">Thống kê</span> ( <span class="from">01/06/2020</span> - <span class="to">16/06/2020</span> )</p>
        </div>
        <div class="content scrollbarX">
            <table class="table">
                <thead>
                    <tr>
                        <td rowspan="2">STT</td>
                        <td rowspan="2">Mã khách hàng</td>
                        <td rowspan="2">Tên khách hàng</td>
                        <td rowspan="2">Điện thoại</td>
                        <td rowspan="2">Tổng đơn</td>
                        <td colspan="3">Đơn chưa gửi</td>
                        <td colspan="3">Đơn chưa nhận</td>
                        <td colspan="3">Đơn đã nhận</td>
                        <td colspan="3">Đơn hủy / boom</td>
                    </tr>
                    <tr class="transparent">
                        <td class="sort sort-both" data-subkey="billsUnsend">Số đơn</td>
                        <td class="sort sort-both" data-subkey="amountUnsend">Sản phẩm</td>
                        <td class="sort sort-both" data-subkey="priceUnsend">Số tiền</td>
                        <td class="sort sort-both" data-subkey="billsUnsuccess">Số đơn</td>
                        <td class="sort sort-both" data-subkey="amountUnsuccess">Sản phẩm</td>
                        <td class="sort sort-both" data-subkey="priceUnsuccess">Số tiền</td>
                        <td class="sort sort-both" data-subkey="billsSuccess">Số đơn</td>
                        <td class="sort sort-both" data-subkey="amountSuccess">Sản phẩm</td>
                        <td class="sort sort-both" data-subkey="priceSuccess">Số tiền</td>
                        <td class="sort sort-both" data-subkey="billsCancel">Số đơn</td>
                        <td class="sort sort-both" data-subkey="amountCancel">Sản phẩm</td>
                        <td class="sort sort-both" data-subkey="priceCancel">Số tiền</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>2310</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2310" title="Huỳnh Giàu" alt="huynh giau" target="_blank">Huỳnh Giàu</a></td>
                        <td>0347219712</td>
                        <td>6</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>150.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>336</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=336" title="Thanh Mai Duong" alt="thanh mai duong" target="_blank">Thanh Mai Duong</a></td>
                        <td>0377773831</td>
                        <td>9</td>
                        <td>1</td>
                        <td>1</td>
                        <td>95.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>445</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=445" title="Lãng Quên" alt="lang quen" target="_blank">Lãng Quên</a></td>
                        <td>0372676124</td>
                        <td>7</td>
                        <td>1</td>
                        <td>1</td>
                        <td>175.000</td>
                        <td>1</td>
                        <td>5</td>
                        <td>768.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>2488</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2488" title="Thuy Nguyen" alt="thuy nguyen" target="_blank">Thuy Nguyen</a></td>
                        <td>0903190648</td>
                        <td>7</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>400.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>3094</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3094" title="Võ Vĩnh Thắng" alt="vo vinh thang" target="_blank">Võ Vĩnh Thắng</a></td>
                        <td>0975026797</td>
                        <td>1</td>
                        <td>1</td>
                        <td>1</td>
                        <td>130.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>2845</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2845" title="Hau Ngoc" alt="hau ngoc" target="_blank">Hau Ngoc</a></td>
                        <td>0388831861</td>
                        <td>4</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>4</td>
                        <td>725.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>2940</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2940" title="Bi Jum" alt="bi jum" target="_blank">Bi Jum</a></td>
                        <td>0964566450</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>250.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>2923</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2923" title="Đỗ Nga" alt="do nga" target="_blank">Đỗ Nga</a></td>
                        <td>0838999978</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>3</td>
                        <td>525.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td>2707</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2707" title="Chi Pham" alt="chi pham" target="_blank">Chi Pham</a></td>
                        <td>0903624922</td>
                        <td>14</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>2</td>
                        <td>5</td>
                        <td>570.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>2951</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2951" title="Yến Ngọc" alt="yen ngoc" target="_blank">Yến Ngọc</a></td>
                        <td>0903931995</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>235.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>961</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=961" title="Luca Rita Nguyen" alt="luca rita nguyen" target="_blank">Luca Rita Nguyen</a></td>
                        <td>0908094220</td>
                        <td>9</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>4</td>
                        <td>600.000</td>
                        <td>1</td>
                        <td>7</td>
                        <td>1.260.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>12</td>
                        <td>2224</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2224" title="Thuỳ Dương Lê" alt="thuy duong le" target="_blank">Thuỳ Dương Lê</a></td>
                        <td>0393794848</td>
                        <td>7</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>175.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>13</td>
                        <td>2403</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2403" title="Trucgiang Nguyen" alt="trucgiang nguyen" target="_blank">Trucgiang Nguyen</a></td>
                        <td>0363472398</td>
                        <td>4</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>3</td>
                        <td>475.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>14</td>
                        <td>2255</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2255" title="Nhung Vo" alt="nhung vo" target="_blank">Nhung Vo</a></td>
                        <td>0942948657</td>
                        <td>6</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>300.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>15</td>
                        <td>2559</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2559" title="Van Pham" alt="van pham" target="_blank">Van Pham</a></td>
                        <td>0932966889</td>
                        <td>4</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>250.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>16</td>
                        <td>349</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=349" title="Mê Gym" alt="me gym" target="_blank">Mê Gym</a></td>
                        <td>0907235353</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>440.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>17</td>
                        <td>392</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=392" title="Hoa Nấm" alt="hoa nam" target="_blank">Hoa Nấm</a></td>
                        <td>0938115177</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>345.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>18</td>
                        <td>3112</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3112" title="Thảo Nguyên" alt="thao nguyen" target="_blank">Thảo Nguyên</a></td>
                        <td>0777438331</td>
                        <td>1</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>165.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>19</td>
                        <td>97</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=97" title="Sầu Riêng" alt="sau rieng" target="_blank">Sầu Riêng</a></td>
                        <td>0939640400</td>
                        <td>7</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>195.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>20</td>
                        <td>2389</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2389" title="Pham Nhi" alt="pham nhi" target="_blank">Pham Nhi</a></td>
                        <td>0942171939</td>
                        <td>8</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>435.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>21</td>
                        <td>3117</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3117" title="Trần Dương" alt="tran duong" target="_blank">Trần Dương</a></td>
                        <td>0984198025</td>
                        <td>1</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>190.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>22</td>
                        <td>3118</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3118" title="Nguyễn Thị Ngọc Bích" alt="nguyen thi ngoc bich" target="_blank">Nguyễn Thị Ngọc Bích</a></td>
                        <td>0939108115</td>
                        <td>1</td>
                        <td>1</td>
                        <td>1</td>
                        <td>190.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>23</td>
                        <td>3074</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3074" title="Bình Yên" alt="binh yen" target="_blank">Bình Yên</a></td>
                        <td>0903924883</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>210.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>24</td>
                        <td>3121</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3121" title="Ngathanh Giang" alt="ngathanh giang" target="_blank">Ngathanh Giang</a></td>
                        <td>0982474373</td>
                        <td>1</td>
                        <td>1</td>
                        <td>3</td>
                        <td>540.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>25</td>
                        <td>3124</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3124" title="Mai Phương" alt="mai phuong" target="_blank">Mai Phương</a></td>
                        <td>0896457486</td>
                        <td>1</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>3</td>
                        <td>260.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>26</td>
                        <td>625</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=625" title="Hồ Thị Dung" alt="ho thi dung" target="_blank">Hồ Thị Dung</a></td>
                        <td>0978738599</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>185.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>27</td>
                        <td>2642</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2642" title="Hiền Nguyễn" alt="hien nguyen" target="_blank">Hiền Nguyễn</a></td>
                        <td>0902739614</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>370.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>28</td>
                        <td>3068</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=3068" title="Nguyen Thị Huỳnh Như" alt="nguyen thi huynh nhu" target="_blank">Nguyen Thị Huỳnh Như</a></td>
                        <td>0377160041</td>
                        <td>2</td>
                        <td>1</td>
                        <td>1</td>
                        <td>85.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>29</td>
                        <td>2484</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2484" title="Rita Bui" alt="rita bui" target="_blank">Rita Bui</a></td>
                        <td>0348956626</td>
                        <td>3</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>260.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>30</td>
                        <td>2260</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2260" title="My Hoang" alt="my hoang" target="_blank">My Hoang</a></td>
                        <td>0377400057</td>
                        <td>14</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>1</td>
                        <td>240.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>31</td>
                        <td>927</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=927" title="Loj Nopj Tran" alt="loj nopj tran" target="_blank">Loj Nopj Tran</a></td>
                        <td>0941311613</td>
                        <td>1</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>3</td>
                        <td>365.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>32</td>
                        <td>2240</td>
                        <td><a href="quan-ly-don-hang.html&amp;kh=2240" title="Nguyễn Thị Như Ngọc" alt="nguyen thi nhu ngoc" target="_blank">Nguyễn Thị Như Ngọc</a></td>
                        <td>0986956516</td>
                        <td>4</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>1</td>
                        <td>2</td>
                        <td>205.000</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="control" data-filter="statistical">
        <input type="button" class="input small hover" name="export" value="Xuất Excel" title="Xuất thành tập tin Excel" />
    </div>
</div>
